### PR TITLE
Add toggleAll and openAll

### PR DESCRIPTION
**Pull request by tikotzky**

### CODE REVIEW

**Comment by kpeatt** [comment]
Hi @tikotzky! Thanks very much for your PR! Would you be willing to write up a short description of your changes and the idea behind the features ala [our contributing guidelines](https://github.com/mobify/bellows/blob/master/CONTRIBUTING.md)? It will help us assess whether this should make it back into the main branch. Again, thanks so much.

**Comment by tikotzky** [comment]
Hi @kpeatt, I bumped the version #, and here's a quick description.

- add ability to openAll by executing `$element.bellows('openAll');` This will loop through all elements to do not currently have the `bellows--is-open` class and call `plugin.open()` on each el.

- add ability to toggleAll by executing `$element.bellows('toggleAll');` This will loop through all elements and toggle their current state.

This 2 actions were added to complement `$element.bellows('closeAll');` which already exists.

**Comment by scalvert** [comment]
@tikotzky looks good!

:+1:

**Comment by kpeatt** [comment]
@tikotzky Great work! Do you mind if I ask what projects you're looking at implementing Bellows on? Always curious to see how it's being used.

**Comment by tikotzky** [comment]
@kpeatt We've been trying to switch to it on https://beta.qualitybath.com

**Comment by kpeatt** [comment]
@tikotzky Wow, awesome! Site is looking great. If we had a section of featured sites using Bellows, would you be willing to let us feature you on it?

**Comment by tikotzky** [comment]
Sure

**Pull request merged**
